# Curated Skills Taxonomy for Chaatra Patha (छात्रपथः)

SKILLS_DICTIONARY = {
    "Soft & Interpersonal Skills": [
        "Effective Communication",
        "Active Listening",
        "Emotional Intelligence (EQ)",
        "Empathy",
        "Teamwork and Collaboration",
        "Conflict Resolution",
        "Adaptability and Flexibility",
        "Problem-Solving",
        "Critical Thinking",
        "Time Management",
        "Creativity and Innovation",
        "Resilience and Grit",
        "Strong Work Ethic",
        "Networking",
        "Persuasion and Negotiation",
        "Interpersonal Skills",
        "Customer-Centric Thinking",
        "Self-Motivation",
        "Cross-Cultural Competence",
        "Dependability",
    ],
    "Leadership & Management": [
        "Project Management",
        "Strategic Planning",
        "Decision Making",
        "Delegation",
        "Mentoring and Coaching",
        "Agile and Scrum Methodologies",
        "Change Management",
        "Performance Management",
        "Public Speaking",
        "Talent Acquisition",
    ],
    "Technology, IT & Software": [
        "Programming/Coding (Python, Java, C++)",
        "Web Development (HTML, CSS, JavaScript)",
        "Cloud Computing (AWS, Azure, GCP)",
        "Cybersecurity and Information Security",
        "Artificial Intelligence (AI) Literacy",
        "Machine Learning Algorithms",
        "DevOps Practices",
        "Mobile App Development (iOS/Android)",
        "API Integration and Development",
        "Network Administration",
        "System Administration (Linux/Windows)",
        "Version Control (Git/GitHub)",
        "Quality Assurance (QA) and Testing",
        "Blockchain Technology",
        "Internet of Things (IoT) Development",
        "Technical Support and Troubleshooting",
        "Database Administration",
        "Prompt Engineering (for Generative AI)",
        "Server Maintenance",
        "Software Architecture",
    ],
    "Data & Analytics": [
        "Data Analysis",
        "Data Visualization (Tableau, Power BI)",
        "Statistical Analysis",
        "Big Data Processing (Hadoop, Spark)",
        "Data Engineering",
        "Predictive Modeling",
        "Business Intelligence (BI)",
        "Data Mining",
        "SQL (Structured Query Language)",
        "Quantitative Research",
    ],
    "Marketing, Sales & Content": [
        "Search Engine Optimization (SEO)",
        "Search Engine Marketing (SEM/PPC)",
        "Content Marketing",
        "Copywriting",
        "Social Media Management",
        "Email Marketing",
        "Customer Relationship Management (CRM) Software",
        "Lead Generation",
        "B2B / B2C Sales",
        "Market Research",
        "Brand Management",
        "Digital Marketing Strategy",
        "E-commerce Management",
        "Public Relations (PR)",
        "Video Marketing",
    ],
    "Business, Finance & Operations": [
        "Financial Accounting (GAAP, IFRS)",
        "Financial Modeling and Forecasting",
        "Budgeting and Cost Management",
        "Risk Management",
        "Supply Chain Management",
        "Inventory Control",
        "Quality Control and Assurance",
        "Business Analysis",
        "Contract Negotiation",
        "Compliance and Regulatory Knowledge",
    ],
    "Design, Creative & Media": [
        "Graphic Design",
        "Adobe Creative Suite (Photoshop, Illustrator)",
        "Video Production and Editing",
        "User Interface (UI) Design",
        "User Experience (UX) Research",
        "3D Modeling and Animation",
        "Photography",
        "Typography",
        "Wireframing and Prototyping (Figma)",
        "Audio Engineering and Editing",
    ],
    "Specialized & Emerging Fields": [
        "Sustainability and ESG Strategy",
        "Augmented Reality (AR) and Virtual Reality (VR) Development",
        "Quantum Computing Basics",
        "Bioinformatics",
        "Renewable Energy Technologies",
    ],
}

# Flat list of all valid skills
ALL_SKILLS_LIST = [
    skill for skills in SKILLS_DICTIONARY.values() for skill in skills
]

# Lowercase lookup dictionary for case-insensitive matching
SKILLS_LOOKUP = {skill.lower(): skill for skill in ALL_SKILLS_LIST}

